---

- name: Apache Installation and Configuration
  hosts: webservers
  become: yes
  vars_files:
    - roles/apache/vars/main.yaml
  roles:
    - apache

- name: File Transfer
  hosts: source,destination
  become: yes
  roles:
    - file_transfer

