---

- name: Apache Installation and Configuration
  hosts: webservers
  become: yes
  vars_files:
    - roles/apache/vars/main.yaml
  roles:
    - apache

- name: File Transfer - Fetch from source and copy to destination
  hosts: source
  roles:
    - source_transfer

- name: Copy file to destination server
  hosts: destination
  roles:
    - destination_transfer

